import formActions from "./formActions";
import formMutations from "./formMutations";
import { v4 as uuid } from "uuid";
export default {
  namespaced: true,
  state: {
    layoutSettings: {
      backgroundColor: "white",
      fontFamily: "'Open Sans', sans-serif",
      fontSize: 16,
      color: "black",
      form: {
        action: "",
        method: "GET",
      },
      input: {
        isOutsideLabel: true,
        labelPosition: "top",
        labelSize: 16,
        labelWidth: 10,
        labelBold: true,
        labelItalic: false,
        labelTopMargin: 0,
        labelBottomMargin: 0,
        labelLeftMargin: 0,
        labelRightMargin: 0,
      },
    },
    elements: [
      {
        rowId: uuid(),
        name: "Title",
        type: "Title",
        properties: {
          general: { backgroundColor: "rgba(0,0,0,0)", fontFamily: "Inherit" },
          text: {
            value: "SAMPLE FORM",
            color: "black",
            size: 40,
            weight: 700,
            style: "normal",
            decoration: "none",
          },
          spacing: {
            align: "center",
            width: 50,
            height: 50,
            fullMargin: false,
            allSidesMargin: 0,
            topMargin: 0,
            rightMargin: 0,
            bottomMargin: 0,
            leftMargin: 0,
          },
        },
        settings: ["general", "spacing", "text"],
      },
      {
        rowId: uuid(),
        type: "Input",
        properties: {
          general: {
            backgroundColor: "rgba(0,0,0,0)",
            fontFamily: "Inherit",
            label: {
              labelTopMargin: 0,
              labelRightMargin: 0,
              labelLeftMargin: 0,
              labelBottomMargin: 0,
              inheritLabelMargin: true,
            },
          },
          border: {
            fullWidth: false,
            allSidesWidth: 1,
            topWidth: 1,
            rightWidth: 1,
            bottomWidth: 1,
            leftWidth: 1,
            style: "solid",
            color: "black",
            radius: 0,
          },
          text: {
            fieldName: "Name",
            placeholder: "Enter Your Name",
            name: "",
            color: "black",
            size: 16,
            inheritSize: true,
            inheritColor: true,
            align: "left",
            weight: 600,
            style: "italic",
          },
          spacing: {
            backgroundColor: "white",
            width: 72,
            height: 35,
            align: "left",
            fullPadding: false,
            allSidesPadding: 5,
            topPadding: 0,
            rightPadding: 0,
            bottomPadding: 0,
            leftPadding: 0,
            fullMargin: false,
            allSidesMargin: 0,
            topMargin: 0,
            rightMargin: 0,
            bottomMargin: 0,
            leftMargin: 0,
          },
        },
        settings: ["general", "spacing", "text", "border"],
      },
      {
        rowId: uuid(),
        type: "Input",
        properties: {
          general: {
            backgroundColor: "rgba(0,0,0,0)",
            fontFamily: "Inherit",
            label: {
              labelTopMargin: 0,
              labelRightMargin: 0,
              labelLeftMargin: 0,
              labelBottomMargin: 0,
              inheritLabelMargin: true,
            },
          },
          border: {
            fullWidth: false,
            allSidesWidth: 1,
            topWidth: 1,
            rightWidth: 1,
            bottomWidth: 1,
            leftWidth: 1,
            style: "solid",
            color: "black",
            radius: 0,
          },
          text: {
            fieldName: "Email",
            placeholder: "Enter Your Email",
            name: "",
            color: "black",
            size: 16,
            inheritSize: true,
            inheritColor: true,
            align: "left",
            weight: 600,
            style: "italic",
          },
          spacing: {
            backgroundColor: "white",
            width: 72,
            height: 35,
            align: "left",
            fullPadding: false,
            allSidesPadding: 5,
            topPadding: 0,
            rightPadding: 0,
            bottomPadding: 0,
            leftPadding: 0,
            fullMargin: false,
            allSidesMargin: 0,
            topMargin: 0,
            rightMargin: 0,
            bottomMargin: 0,
            leftMargin: 0,
          },
        },
        settings: ["general", "spacing", "text", "border"],
      },
      {
        rowId: uuid(),
        type: "Button",
        properties: {
          general: {
            backgroundColor: "rgba(0,0,0,0)",
            fontFamily: "Inherit",
          },
          fullPadding: false,
          border: {
            fullWidth: false,
            allSidesWidth: 1,
            topWidth: 1,
            rightWidth: 1,
            bottomWidth: 1,
            leftWidth: 1,
            style: "solid",
            color: "black",
            radius: 5,
          },
          text: {
            value: "Send Information",
            color: "black",
            size: 16,
            inheritSize: true,
            inheritColor: true,
            align: "center",
            weight: 600,
            style: "normal",
            decoration: "none",
          },
          spacing: {
            backgroundColor: "white",
            width: 30,
            height: 50,
            align: "center",
            fullPadding: false,
            allSidesPadding: 0,
            topPadding: 0,
            rightPadding: 0,
            bottomPadding: 0,
            leftPadding: 0,
            fullMargin: false,
            allSidesMargin: 0,
            topMargin: 0,
            rightMargin: 0,
            bottomMargin: 0,
            leftMargin: 0,
          },
        },
        settings: ["general", "spacing", "text", "border"],
      },
    ],
    previousStates: [],
    nextStates: [],
  },
  actions: formActions,
  mutations: formMutations,
};
